// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.learn.netty.grpc;

public final class StuInfo {
  private StuInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreamRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.learn.netty.grpc.StreamRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string request_info = 1;</code>
     */
    java.lang.String getRequestInfo();
    /**
     * <code>string request_info = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestInfoBytes();
  }
  /**
   * Protobuf type {@code com.learn.netty.grpc.StreamRequest}
   */
  public  static final class StreamRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.learn.netty.grpc.StreamRequest)
      StreamRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamRequest.newBuilder() to construct.
    private StreamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamRequest() {
      requestInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestInfo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.netty.grpc.StuInfo.StreamRequest.class, com.learn.netty.grpc.StuInfo.StreamRequest.Builder.class);
    }

    public static final int REQUEST_INFO_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestInfo_;
    /**
     * <code>string request_info = 1;</code>
     */
    public java.lang.String getRequestInfo() {
      java.lang.Object ref = requestInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string request_info = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestInfoBytes() {
      java.lang.Object ref = requestInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learn.netty.grpc.StuInfo.StreamRequest)) {
        return super.equals(obj);
      }
      com.learn.netty.grpc.StuInfo.StreamRequest other = (com.learn.netty.grpc.StuInfo.StreamRequest) obj;

      if (!getRequestInfo()
          .equals(other.getRequestInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getRequestInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learn.netty.grpc.StuInfo.StreamRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learn.netty.grpc.StuInfo.StreamRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.learn.netty.grpc.StreamRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.learn.netty.grpc.StreamRequest)
        com.learn.netty.grpc.StuInfo.StreamRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learn.netty.grpc.StuInfo.StreamRequest.class, com.learn.netty.grpc.StuInfo.StreamRequest.Builder.class);
      }

      // Construct using com.learn.netty.grpc.StuInfo.StreamRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestInfo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamRequest_descriptor;
      }

      @java.lang.Override
      public com.learn.netty.grpc.StuInfo.StreamRequest getDefaultInstanceForType() {
        return com.learn.netty.grpc.StuInfo.StreamRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.learn.netty.grpc.StuInfo.StreamRequest build() {
        com.learn.netty.grpc.StuInfo.StreamRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learn.netty.grpc.StuInfo.StreamRequest buildPartial() {
        com.learn.netty.grpc.StuInfo.StreamRequest result = new com.learn.netty.grpc.StuInfo.StreamRequest(this);
        result.requestInfo_ = requestInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learn.netty.grpc.StuInfo.StreamRequest) {
          return mergeFrom((com.learn.netty.grpc.StuInfo.StreamRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learn.netty.grpc.StuInfo.StreamRequest other) {
        if (other == com.learn.netty.grpc.StuInfo.StreamRequest.getDefaultInstance()) return this;
        if (!other.getRequestInfo().isEmpty()) {
          requestInfo_ = other.requestInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learn.netty.grpc.StuInfo.StreamRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learn.netty.grpc.StuInfo.StreamRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestInfo_ = "";
      /**
       * <code>string request_info = 1;</code>
       */
      public java.lang.String getRequestInfo() {
        java.lang.Object ref = requestInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string request_info = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestInfoBytes() {
        java.lang.Object ref = requestInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string request_info = 1;</code>
       */
      public Builder setRequestInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string request_info = 1;</code>
       */
      public Builder clearRequestInfo() {
        
        requestInfo_ = getDefaultInstance().getRequestInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string request_info = 1;</code>
       */
      public Builder setRequestInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestInfo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.learn.netty.grpc.StreamRequest)
    }

    // @@protoc_insertion_point(class_scope:com.learn.netty.grpc.StreamRequest)
    private static final com.learn.netty.grpc.StuInfo.StreamRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learn.netty.grpc.StuInfo.StreamRequest();
    }

    public static com.learn.netty.grpc.StuInfo.StreamRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamRequest>
        PARSER = new com.google.protobuf.AbstractParser<StreamRequest>() {
      @java.lang.Override
      public StreamRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learn.netty.grpc.StuInfo.StreamRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StreamResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.learn.netty.grpc.StreamResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response_info = 1;</code>
     */
    java.lang.String getResponseInfo();
    /**
     * <code>string response_info = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseInfoBytes();
  }
  /**
   * Protobuf type {@code com.learn.netty.grpc.StreamResponse}
   */
  public  static final class StreamResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.learn.netty.grpc.StreamResponse)
      StreamResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamResponse.newBuilder() to construct.
    private StreamResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamResponse() {
      responseInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseInfo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.netty.grpc.StuInfo.StreamResponse.class, com.learn.netty.grpc.StuInfo.StreamResponse.Builder.class);
    }

    public static final int RESPONSE_INFO_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseInfo_;
    /**
     * <code>string response_info = 1;</code>
     */
    public java.lang.String getResponseInfo() {
      java.lang.Object ref = responseInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string response_info = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseInfoBytes() {
      java.lang.Object ref = responseInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learn.netty.grpc.StuInfo.StreamResponse)) {
        return super.equals(obj);
      }
      com.learn.netty.grpc.StuInfo.StreamResponse other = (com.learn.netty.grpc.StuInfo.StreamResponse) obj;

      if (!getResponseInfo()
          .equals(other.getResponseInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getResponseInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learn.netty.grpc.StuInfo.StreamResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learn.netty.grpc.StuInfo.StreamResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.learn.netty.grpc.StreamResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.learn.netty.grpc.StreamResponse)
        com.learn.netty.grpc.StuInfo.StreamResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learn.netty.grpc.StuInfo.StreamResponse.class, com.learn.netty.grpc.StuInfo.StreamResponse.Builder.class);
      }

      // Construct using com.learn.netty.grpc.StuInfo.StreamResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseInfo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learn.netty.grpc.StuInfo.internal_static_com_learn_netty_grpc_StreamResponse_descriptor;
      }

      @java.lang.Override
      public com.learn.netty.grpc.StuInfo.StreamResponse getDefaultInstanceForType() {
        return com.learn.netty.grpc.StuInfo.StreamResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.learn.netty.grpc.StuInfo.StreamResponse build() {
        com.learn.netty.grpc.StuInfo.StreamResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learn.netty.grpc.StuInfo.StreamResponse buildPartial() {
        com.learn.netty.grpc.StuInfo.StreamResponse result = new com.learn.netty.grpc.StuInfo.StreamResponse(this);
        result.responseInfo_ = responseInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learn.netty.grpc.StuInfo.StreamResponse) {
          return mergeFrom((com.learn.netty.grpc.StuInfo.StreamResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learn.netty.grpc.StuInfo.StreamResponse other) {
        if (other == com.learn.netty.grpc.StuInfo.StreamResponse.getDefaultInstance()) return this;
        if (!other.getResponseInfo().isEmpty()) {
          responseInfo_ = other.responseInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learn.netty.grpc.StuInfo.StreamResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learn.netty.grpc.StuInfo.StreamResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseInfo_ = "";
      /**
       * <code>string response_info = 1;</code>
       */
      public java.lang.String getResponseInfo() {
        java.lang.Object ref = responseInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response_info = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseInfoBytes() {
        java.lang.Object ref = responseInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_info = 1;</code>
       */
      public Builder setResponseInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response_info = 1;</code>
       */
      public Builder clearResponseInfo() {
        
        responseInfo_ = getDefaultInstance().getResponseInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string response_info = 1;</code>
       */
      public Builder setResponseInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseInfo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.learn.netty.grpc.StreamResponse)
    }

    // @@protoc_insertion_point(class_scope:com.learn.netty.grpc.StreamResponse)
    private static final com.learn.netty.grpc.StuInfo.StreamResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learn.netty.grpc.StuInfo.StreamResponse();
    }

    public static com.learn.netty.grpc.StuInfo.StreamResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamResponse>
        PARSER = new com.google.protobuf.AbstractParser<StreamResponse>() {
      @java.lang.Override
      public StreamResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learn.netty.grpc.StuInfo.StreamResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_learn_netty_grpc_StreamRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_learn_netty_grpc_StreamRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_learn_netty_grpc_StreamResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_learn_netty_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\024com.learn.netty.grpc\"%\n" +
      "\rStreamRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016" +
      "StreamResponse\022\025\n\rresponse_info\030\001 \001(\t2k\n" +
      "\016StudentService\022Y\n\006BiTalk\022#.com.learn.ne" +
      "tty.grpc.StreamRequest\032$.com.learn.netty" +
      ".grpc.StreamResponse\"\000(\0010\001B\037\n\024com.learn." +
      "netty.grpcB\007StuInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_learn_netty_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_learn_netty_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_learn_netty_grpc_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_learn_netty_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_learn_netty_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_learn_netty_grpc_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
